---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-user-app
  namespace: assignment
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/skolichala/application-repo.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hello-user-app
  namespace: assignment
spec:
  interval: 1m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: hello-user-app

